schedule:
  year: "2022"
  program: java
  lessons:
    - date: "2022-02-01"
      startTime: "08:00"
      endTime: "12:00"
      description: "Devops"
    - date: "2022-02-02"
      startTime: "08:00"
      endTime: "12:00"
      description: "Working with Devops"
