schedule:
  year: "2023"  
  program: "Java Programming"
  lessons:
    - date: "2023-09-15"
      description: "Introduction to Java basics"
    - date: "2023-09-16"
      description: "Working with Java variables"
